artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion/raw
  source_URL: https://drive.google.com/file/d/1H5_TNw4NGCcigiEp8WZN5kiRF6iRqhAT/view
  local_data_file: artifacts/data_ingestion/raw/data.zip
  unzipped_data_dir: artifacts/data_ingestion/raw

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/raw/hiv_dataset/HIV.csv
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv

data_preparation:
  root_dir: artifacts/data_preparation
  train_csv_path: artifacts/data_transformation/train.csv
  test_csv_path: artifacts/data_transformation/test.csv
  train_graph_dir: artifacts/data_preparation/train_graphs
  test_graph_dir: artifacts/data_preparation/test_graphs

